-- MySQL Script generated by MySQL Workbench
-- 04/19/21 11:25:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Lot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lot` (
  `id_lot` INT NOT NULL,
  `id_samolot` INT NULL,
  `id_lotnisko` INT NULL,
  `id_user` INT NULL,
  `cel` VARCHAR(45) NULL,
  `czas` DATETIME NULL,
  PRIMARY KEY (`id_lot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Samoloty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Samoloty` (
  `id_samolot` INT NOT NULL,
  `nazwa` VARCHAR(45) NULL,
  `pojemnosc` INT NULL,
  `Lot_id_lotu` INT NOT NULL,
  PRIMARY KEY (`id_samolot`),
  INDEX `fk_Samoloty_Lot_idx` (`Lot_id_lotu` ASC),
  CONSTRAINT `fk_Samoloty_Lot`
    FOREIGN KEY (`Lot_id_lotu`)
    REFERENCES `mydb`.`Lot` (`id_lot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lotniska`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lotniska` (
  `id_lotnisko` INT NOT NULL,
  `nazwa` VARCHAR(45) NULL,
  `miejsce` VARCHAR(45) NULL,
  `Lot_id_lotu` INT NOT NULL,
  PRIMARY KEY (`id_lotnisko`),
  INDEX `fk_Lotniska_Lot1_idx` (`Lot_id_lotu` ASC),
  CONSTRAINT `fk_Lotniska_Lot1`
    FOREIGN KEY (`Lot_id_lotu`)
    REFERENCES `mydb`.`Lot` (`id_lot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bilet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bilet` (
  `id_bilet` INT NOT NULL,
  `id_lot` VARCHAR(45) NULL,
  `cena` VARCHAR(45) NULL,
  `ilosc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_bilet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bilet_zakupiony`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bilet_zakupiony` (
  `id_bilet_zakupiony` INT NOT NULL,
  `id_bilet` INT NULL,
  `id_user` INT NULL,
  `Bilet_id_bilet` INT NOT NULL,
  PRIMARY KEY (`id_bilet_zakupiony`),
  INDEX `fk_Bilet_zakupiony_Bilet1_idx` (`Bilet_id_bilet` ASC),
  CONSTRAINT `fk_Bilet_zakupiony_Bilet1`
    FOREIGN KEY (`Bilet_id_bilet`)
    REFERENCES `mydb`.`Bilet` (`id_bilet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id_user` INT NOT NULL,
  `Imię` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `typ` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `haslo` VARCHAR(45) NULL,
  `id_lot` VARCHAR(45) NULL,
  `Lot_id_lot` INT NOT NULL,
  `Bilet_zakupiony_id_bilet_zakupiony` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_Users_Lot1_idx` (`Lot_id_lot` ASC),
  INDEX `fk_Users_Bilet_zakupiony1_idx` (`Bilet_zakupiony_id_bilet_zakupiony` ASC),
  CONSTRAINT `fk_Users_Lot1`
    FOREIGN KEY (`Lot_id_lot`)
    REFERENCES `mydb`.`Lot` (`id_lot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_Bilet_zakupiony1`
    FOREIGN KEY (`Bilet_zakupiony_id_bilet_zakupiony`)
    REFERENCES `mydb`.`Bilet_zakupiony` (`id_bilet_zakupiony`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view2` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


-- -----------------------------------------------------
-- View `mydb`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view2`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
